@AddMember_HostAddress = https://addmember.graysand-d4eec930.eastus2.azurecontainerapps.io/
@Docker_HostAddress = http://localhost:8080

### Request for children
POST {{AddMember_HostAddress}}/addmember?name=Romina&lastname=Ludueña&birthyear=2014
Content-Type: application/json
Accept: application/json

###
POST {{Docker_HostAddress}}/addmember?name=Magaly&lastname=Petra&birthyear=2015
Content-Type: application/json
Accept: application/json

### Request for adults
POST {{AddMember_HostAddress}}/addmember?name=Roberto&lastname=Martinez&birthyear=1979
Content-Type: application/json
Accept: application/json

###
POST {{Docker_HostAddress}}/addmember?name=Roberto&lastname=Martinez&birthyear=1979
Content-Type: application/json
Accept: application/json