@GetChildren_HostAddress = https://getchildren.graysand-d4eec930.eastus2.azurecontainerapps.io/
@Docker_HostAddress = http://localhost:4000

GET {{GetChildren_HostAddress}}/Children/
Accept: application/json

###
GET {{Docker_HostAddress}}/Children/
Accept: application/json